name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_exe:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: hecrj/setup-rust-action@v1
      - uses: actions/download-artifact@v4.1.7

      - if: matrix.os == 'ubuntu-latest'
        run: |
          rustup target add x86_64-unknown-linux-musl
          sudo apt-get -qq install musl-tools
      - if: matrix.os == 'ubuntu-latest'
        run: make release_lnx VERSION=${{github.ref_name}}
        shell: sh

      - if: matrix.os == 'macOS-latest'
        run: |
          rustup target add x86_64-apple-darwin
          make release_mac_x86_64  VERSION=${{github.ref_name}}
          make release_mac_aarch64 VERSION=${{github.ref_name}}
        shell: sh

      - if: matrix.os == 'windows-latest'
        run: make release_win VERSION=${{github.ref_name}}
        shell: bash

      - uses: softprops/action-gh-release@v1
        with:
          body: '[Changelog](https://github.com/dalance/svlint/blob/master/CHANGELOG.md)'
          files: '*.zip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
